<?php

/**
 * Created by PhpStorm.
 * User: Francesco
 * Date: 15/04/19
 * Time: 12:48
 */
class PostsController extends ApiController
{
    protected static $defaulLimit = 30;

    protected static $defaultOrderBy = null;

    protected static $defaultPage = 1;

    protected static $defaultSearch = null;

    private $listFilters = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function tipologiePostsAction(){
        return $this->response->setJsonContent(
            TipologiePost::find([
                'columns' => 'id, descrizione, slug, ordine',
                'hydration' => \Phalcon\Mvc\Model\Resultset::HYDRATE_ARRAYS,
                'cache' => [
                    "key" => "apiTipologiePostsAction",
                    "lifetime" => 36000
                ]
            ])
        );
    }





}